### ISSUE TITLE
lldpad generated core dump with SIGSEGV in dcbx_unregister

### ISSUE THREAD

**Issue by SrijitNair** [openSUSE/lldpad#4]
Hi,
The lldp on my alma crashed with a core dump.
The analysis gives the following trace 
"
Core was generated by `/usr/sbin/lldpad -t'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000056219c1628ce in dcbx_unregister ()".

we are using :
lldpad-1.0.1-16.git036e314.el8.x86_64
AlmaLinux release 8.6 (Sky Tiger)

Is there a known bug and a fix ?
Thanks,
Srijit

**Comment by mwilck** [comment]
why are you posting this on openSUSE if it occurs on Alma Linux?
